version: '3.3'
services:
  post_db:    
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit-backend: 
        aliases: 
          - comment_db
          - post_db
  ui:    
    image: '${USERNAME}/ui:${UI_VERSION}'
    ports:
      - '${PORT_HOST}:${PORT_CONTAINER}/tcp'
    networks:
      - reddit-frontend
        
  post:    
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - reddit-frontend
      - reddit-backend

  comment:    
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit-frontend
      - reddit-backend

volumes:
  post_db:

networks:
  reddit-backend:
  reddit-frontend:
